services:
  my-sql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: nguyen123
      MYSQL_DATABASE: ITJOB
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
